package com.revconnect.enums;

public enum NotificationType {
    CONNECTION_REQUEST, CONNECTION_ACCEPTED, NEW_FOLLOWER,
    POST_LIKED, POST_COMMENTED, POST_SHARED, MENTION, SYSTEM, MESSAGE, ADMIN_REPORT
}
